task_2_1_1
L3XxXa/OOP pull request #11
Opened 2022-02-15 16:51 UTC by L3XxXa

Пока нет Джавадоков, по 2 теста на каждый класс, постараюсь поправить до мягкого дедлайна.

2022-02-20 07:38 UTC, L3XxXa commented
Cкорее всего, ломаться в случае, когда мы пытаемся запустить на большем, чем доступном количестве тредов, - очень плохо :)

2022-02-21 10:14 UTC, Leidenn2509 requested changes

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/PrimeChecker.java
> +        for (int j = 5; j * j <= a; j += 6) {
Math.sqrt()

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/PrimeChecker.java
> +    public boolean isPrimeNumber(long a) {
static

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/StreamPrimeChecker.java
> +        List<Long> res = list.parallelStream().filter(this :: notPrime).collect(Collectors.toList());
anyMatch/nonMatch

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/MultiThreadPrimeChecker.java
> +            throw new IndexOutOfBoundsException();
В обычных рабочих классах принтов не должно быть. Принты там где планируется работа с пользователем

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/MultiThreadPrimeChecker.java
> +        for (int i = 0; i < amount; i++) {
Вы amount раз проверяете весь массив

2022-02-21 10:14 UTC, Leidenn2509 commented on task_2_1_1/src/test/java/ru/nsu/malov/MultiThreadPrimeCheckerTest.java
> +    }
Принтов в тестах не должно быть. Всем снаружи важно только прошел тест или нет

2022-03-02 08:44 UTC, Leidenn2509 requested changes

2022-03-02 08:44 UTC, Leidenn2509 commented on task_2_1_1/src/main/java/ru/nsu/malov/MultiThreadPrimeChecker.java
> +    public void MultiThreadChecker(int amount, List<Long> arr) {
Слишком много работы для конструктора

2022-03-02 15:25 UTC, L3XxXa commented
Возможно мне хватит душевных сил, чтобы изучить какой-нибудь условный JFree, чтобы рисовать с помощью джавы графики.

2022-03-03 07:42 UTC, L3XxXa commented
К 20 годам наконец-то научился читать. Переделал немного метрику.

2022-03-10 10:16 UTC, Leidenn2509 approved these changes

2022-03-13 15:37 UTC, merged