task 2.2.1
L3XxXa/OOP pull request #12
Opened 2022-03-13 15:41 UTC by L3XxXa

2022-03-13 15:42 UTC, L3XxXa commented
Вы забыли замерджить пр с прошлой лабой. Ничего, если я сделал это сам?

2022-03-17 07:05 UTC, Leidenn2509 requested changes
По идее должны быть возможны ситуации когда нет заказов и все ждут когда они появятся.

2022-03-17 07:05 UTC, Leidenn2509 commented on task_2_2_1/src/main/java/ru/nsu/malov/workers/Cook.java
> +        while (true){
Так не пойдет

2022-03-17 07:05 UTC, Leidenn2509 commented on task_2_2_1/src/main/java/ru/nsu/malov/Pizzeria.java
> +            wait();
Лучше явно показать на ком вызываете wait. Так просто легче читать

2022-03-27 19:06 UTC, L3XxXa commented
# WIP
 На данный момент, данного кода недостаточно для жесткого дедлайна точно.
 Так как я стараюсь сразу придерживаться SOLID, особенно буковки I, я начал **полностью** переписывать лабу.
 Из-за чего там, по проценту выполненных тасок, есть даже отрицательный прогресс.
 Постараюсь сделать лабу до конца этой недели.

P.S. попытаюсь немного оправдаться: большую часть предыдущей недели я писал проект на Java, только под Андроид, из-за чего немного неправильно распределил время, в следствие чего, времени у меня физически просто не хватило на лабу. Зато хотя бы по проекту огромный прогресс...

2022-04-02 05:00 UTC, L3XxXa commented
Ого какой красивый пр, три исходника со старой версии остались

2022-04-12 01:02 UTC, merged