Task_2_4_1
L3XxXa/OOP pull request #16
Opened 2022-06-03 10:18 UTC by L3XxXa

2022-06-03 10:52 UTC, L3XxXa commented
Вроде как реализовал модель по заданию. Не знаю, что еще надо в нее добавить...

2022-06-05 06:08 UTC, L3XxXa commented
Это пока первая модель, которой достаточно для мягкого дедлайна по идее. 
После того, как прочитал на kotlinlang про dsl, понял, что можно круче сделать.

2022-06-07 11:22 UTC, Leidenn2509 requested changes
Выглядит хорошо. Посмотрим как дальше пойдёт

2022-06-12 11:44 UTC, L3XxXa commented
На моем репозитории чекать надо очень аккуратно, так как я большую часть первого семестра использовал jdk 11 (сейчас 17) Из-за этого невозможно запустить тест лабы.
Я проверял на task _1_1_1. Специально собрал ее с 17 джавой :)
А еще кое-где есть трабла с неймингом проектов, и где-то может быть пробел лишний...

2022-06-12 12:10 UTC, L3XxXa commented
Как оказалось, весь первый семестр. Пересоберу все лабы
сейчас только 1.1.1 с первого семестра была собрана на 17 джаве

2022-06-12 14:50 UTC, L3XxXa commented
Из того, что пересобрал: 1.1.1 и 2.3.1

2022-06-14 06:28 UTC, L3XxXa commented
Пересобрал только змейку для проверки код стайла. Другие должны работать, но просто у меня нет времени пересобрать все лабы для проверки

2022-06-14 15:12 UTC, L3XxXa commented
[5ec7799](https://github.com/L3XxXa/OOP/pull/16/commits/5ec7799ddbb9dbd5be62406911df5f62a1360cd8) - коммит, в котором, по сути, готовая логика. Дальше только джарник + джабадоки

2022-06-14 15:52 UTC, L3XxXa commented
Я буду пытаться сделать второе доп задание. Могу все сломать, поэтому точно рабочий последний коммит [b7e0812](https://github.com/L3XxXa/OOP/pull/16/commits/b7e081278ed519813440c3635ff4a553c6978724)

2022-06-14 15:58 UTC, Leidenn2509 approved these changes
<img width="182" alt="image" src="https://user-images.githubusercontent.com/34095512/173615275-7a339f12-b0f8-4d8d-acd2-f19281fb648e.png">  
шо происходит

# Максимум 2

## Мягкий

- [x] DSL + model

## Main

- [x] DSL
- [x] Clone
- [x] Build
- [x] Test
- [x] Report
- [x] Docs
- [x] Attendance

## Add

### +0.5

- [x] Code style check
- [x] code coverage

### +0.5

- [ ] импорт
- [ ] разбаловка задач
- [ ] дедлайны

2022-06-14 16:01 UTC, Leidenn2509 commented
> Я буду пытаться сделать второе доп задание. Могу все сломать, поэтому точно рабочий последний коммит [b7e0812](https://github.com/L3XxXa/OOP/pull/16/commits/b7e081278ed519813440c3635ff4a553c6978724)

А вам вроде и не нужно

2022-06-14 16:01 UTC, L3XxXa commented on task_2_4_1/configs/AlexeyMalov.kts
> +    }
тестировал блоки, и забыл убрать)

2022-06-14 16:02 UTC, L3XxXa commented
> > Я буду пытаться сделать второе доп задание. Могу все сломать, поэтому точно рабочий последний коммит [b7e0812](https://github.com/L3XxXa/OOP/pull/16/commits/b7e081278ed519813440c3635ff4a553c6978724)
> 
> А вам вроде и не нужно
Да я так, для себя...

2022-06-15 15:37 UTC, merged