Task 4.2
L3XxXa/OOP pull request #7
Opened 2021-11-16 18:59 UTC by L3XxXa

2021-11-17 12:06 UTC, Leidenn2509 requested changes
- Для разбора ком строки советую использовать библиотеку
- Методы `show` должны выдавать список заметок, а не строку

2021-11-17 12:06 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +    Gson gson;
Советую вынести работу с файлами из `Notebook`. Так вам будет проще тестировать

2021-11-17 12:06 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +class Note {
Отдельный файл

2021-11-17 12:06 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +    private String text;
Ещё имя нужно

2021-11-17 12:06 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +    }
Что-то тут не так

2021-11-23 11:50 UTC, L3XxXa commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +    }
странно, у меня почему-то сначала запрос на ревью, а затем залитый коммит, если что, то
 L3XxXa requested a review from Leidenn2509

2021-11-24 12:14 UTC, Leidenn2509 requested changes
javadoc

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Main.java
> +    //TODO Make it works)
Получилось?

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Note.java
> +    private String time;
`LocalDateTime`

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +        return notes;
Нехорошо отдавать настоящий референс на свои данные. Кто-то может из изменить

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +        ArrayList<Note> res = new ArrayList<>();
`List`

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/test/java/ru/nsu/malov/NotebookTest.java
> +class NotebookTest {
Мало

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Json/Application.java
> +            }
Если что-то сломалось и вы перехватили исключение, не нужно просто печатать его и идти дальше. Нужно либо как-то восстановиться (хотя здесь не уверен что можно сделать), либо просто сломаться. Пользователю не интересно смотреть на стек трейс.

2021-11-24 12:14 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Json/Application.java
> +public class Application {
Добавьте help. Непонятно как работают параметры, если не заглядывать в код

2021-11-24 15:03 UTC, L3XxXa commented on task 4.2/src/main/java/ru/nsu/malov/Json/JsonMaker.java
> +    private final String fileName = "Notes.json";
Должен создаваться новый файл, получается?

2021-11-24 15:04 UTC, L3XxXa commented on task 4.2/src/test/java/ru/nsu/malov/NotebookTest.java
> +class NotebookTest {
Я случайно залил с этими тестами. Просто для себя проверял, работает ли верно)

2021-11-24 15:23 UTC, L3XxXa commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +        LocalDateTime beforeLocal = LocalDateTime.parse(before.toString());
Здесь в какой именно строчке?

2021-11-24 15:24 UTC, L3XxXa commented on task 4.2/src/main/java/ru/nsu/malov/Json/Application.java
> +public class Application {
Вывод help message при передаче параметра?

2021-11-24 19:43 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Notebook.java
> +        LocalDateTime beforeLocal = LocalDateTime.parse(before.toString());
Вы получаете `LocalDateTime` и потом преобразуете его в `LocalDateTime`. Зачем?

2021-11-24 19:44 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Json/JsonMaker.java
> +    private final String fileName = "Notes.json";
Для каждой зачётки со своим именем -- свой файл

2021-11-24 19:44 UTC, Leidenn2509 commented on task 4.2/src/main/java/ru/nsu/malov/Json/Application.java
> +public class Application {
Если пользователь ввёл `-h` `--help` или если ничего не ввёл

2021-12-04 11:59 UTC, Leidenn2509 requested changes
Дедлайн зачёл, но приложение очень тяжко использовать в консоли. Потакайте сами и почините все недостатки.

2021-12-04 11:59 UTC, Leidenn2509 commented on task 1.4.2/src/main/java/ru/nsu/malov/json/App.java
> +            e.printStackTrace();
Не нужно. Вы в следующей строчке скажите пользователю "Can't parse your parameters." и ему не нужно смотреть на стектрейс

2022-06-03 09:51 UTC, merged